import type { StoryEpisodeActDefinition } from '../../../episodeTemplate';

export const EPISODE_03_ACT_03 = {
  id: 'ep03.act3-aquarium-and-monday',
  title: '鱼不能离开水',
  trigger: { date: { year: 2008, month: 4, day: 13 }, actionNumber: 1 },
  timeCost: 'whole-day',
  plotLore: {
    worldbookName: '出包王女',
    entryOrder: 157,
    entryName: '剧情第三集·第三幕',
    rootTag: 'To LOVE-Ru TV Episode 03 Act 03',
    kind: 'plot',
  },
  loreSection: '第三幕·鱼不能离开水',
  characterLoreIds: ['lala', 'haruna', 'mikan', 'riko'],
  presentation: {
    sceneIds: ['aquarium', 'schoolRoad'],
    cast: [
      { characterId: 'lala', portraitIds: ['arrival-default'] },
      { characterId: 'haruna', portraitIds: ['school-uniform'] },
      { characterId: 'mikan', portraitIds: ['arrival-default'] },
      { characterId: 'riko', portraitIds: ['school-uniform'] },
    ],
  },
  generation: {
    minimumLineCount: 28,
    requiredSceneSequence: ['aquarium', 'schoolRoad'],
  },
  fallbackBeats: [
    {
      speaker: null,
      text: '星期日，蓝光从一排排水箱里漫出来。菈菈贴着玻璃追鱼，问题一个接一个，美柑只好跟在后面提醒她别走丢。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '抱歉，难得休息还把你卷进来。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '不会。我本来就想和你说话，只是每次都没找到机会。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '美柑来回看了你们一眼，忽然说要去找菈菈。她走得很自然，连回头都没有。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '结城美柑',
      text: '你，春菜姐就交给你了。我去看着菈菈，免得她把鱼带回家。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '你本想把话题轻轻带过，春菜却伸手抓住了你的手臂。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '我说过吧，你和菈菈很般配。菈菈是个很棒的女孩……可是，你也一直很温柔。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '从初中起，你就在照顾教室里的花。没有谁拜托你，是你自己去做的。我一直都看见了。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '我还是觉得你们很般配。可即使这样，我……',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '春菜，我也……',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '另一边，走散的菈菈停在一座安静的水箱前。几条鱼贴着底部不动，她看得直皱眉。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '它们看起来没精神。用狂战士DX应该就会有力气了！',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'flash',
      },
    },
    {
      speaker: null,
      text: '药剂落进水里，鱼群猛地冲上半空。水箱边接连响起撞击声，游客的惊叫从走廊另一头卷了过来。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: '沛凯',
      text: '菈菈大人，鱼离开水会死的！',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'panic',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '原来是这样！那只要把水加回来就好了。增水君，拜托你了！',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'flash',
      },
    },
    {
      speaker: null,
      text: '小象形发明喷出的水转眼没过脚踝，又漫到膝边。两个人同时停在告白开头的话，被巨响和洪水一起截断。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: '结城美柑',
      text: '你，先把人带到高处！别站在那里发愣。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'shake',
      },
    },
    {
      speaker: '你',
      text: '春菜，抓紧我。先去那边的台阶。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: null,
      text: '骚动收场时，四个人都湿透了。菈菈抱着没事的鱼缸松了口气，美柑则开始盘算怎么向工作人员道歉。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '虽然吓了一跳，不过今天真的很开心。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '你和春菜都没有把水族馆里刚刚开始的告白补完。星期日就这样结束了。',
      presentation: {
        sceneId: 'aquarium',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '翌日，四月十四日，星期一。上学路上，你刚看见春菜迎面走来，脚尖便勾住了路沿。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '你和春菜撞作一团，书包和讲义撒了一地。没有浪漫姿势，只有两个人同时慌着道歉。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '你没受伤吧？先、先起来再说。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '梨子蹲下来捡讲义，熟练得像早就料到你会在春菜面前失去平衡。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '夕崎梨子',
      text: '星期一第一件事就平地摔。还好我替你多带了一份讲义。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '你在地球上也会突然飞出去呢！',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '菈菈同学，先帮忙把那边的作业本捡起来吧。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '夕崎梨子',
      text: '别急着顶嘴。你再踩到讲义，今天第一节课就真要迟到了。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '这只是摔倒！别说得像新发明一样！',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'shake',
      },
    },
  ],
} as const satisfies StoryEpisodeActDefinition;
