import type { StoryEpisodeActDefinition } from '../../../episodeTemplate';

export const EPISODE_03_ACT_02 = {
  id: 'ep03.act2-shopping-and-invitation',
  title: '换装能量耗尽',
  trigger: { date: { year: 2008, month: 4, day: 12 }, actionNumber: 1 },
  timeCost: 'whole-day',
  plotLore: {
    worldbookName: '出包王女',
    entryOrder: 156,
    entryName: '剧情第三集·第二幕',
    rootTag: 'To LOVE-Ru TV Episode 03 Act 02',
    requiredContentMarker: '主角身份:User是结城家的养子，也是美柑的老哥',
    kind: 'plot',
  },
  loreSection: '第二幕·换装能量耗尽',
  characterLoreIds: ['lala', 'haruna', 'mikan'],
  presentation: {
    sceneIds: ['townStreet'],
    cast: [
      { characterId: 'lala', portraitIds: ['arrival-default'] },
      { characterId: 'haruna', portraitIds: ['school-uniform'] },
      { characterId: 'mikan', portraitIds: ['arrival-default'] },
    ],
  },
  generation: {
    minimumLineCount: 26,
    requiredSceneSequence: ['townStreet'],
  },
  fallbackBeats: [
    {
      speaker: null,
      text: '星期六的彩南町挤满行人。菈菈的宇宙服在人群里亮得扎眼，每走几步就有人回头。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '这样根本没法低调。沛凯，能不能换成普通一点的衣服？',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '沛凯',
      text: '装束分析完成。换装。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'flash',
      },
    },
    {
      speaker: null,
      text: '西装、警服、玩偶装轮番闪过。你每摇一次头，菈菈就笑得更开心。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'flash',
      },
    },
    {
      speaker: '结城美柑',
      text: '够了，再换下去先累坏的是沛凯。最后这套就很正常。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '地球人的衣服好多呀！每一套都很有趣。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '三人吃过鲷鱼烧，又在抓娃娃机前停下。菈菈隔着玻璃盯住一只旧兔子布偶。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '想要那个？等着，我试一次。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '所谓一次很快变成了十几次。硬币快见底时，夹爪总算勾住兔子的耳朵，把它拖进出口。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '结城美柑',
      text: '老哥也就这种时候特别不肯认输。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '送给我的？我会把它当成宝物！',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '沛凯',
      text: '真是对不起，菈菈大人。刚才换装太多，好像是能量用完了。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: null,
      text: '服装边缘开始忽明忽暗。美柑立刻站到菈菈右边，又把你推到左边挡住路人的视线。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'shake',
      },
    },
    {
      speaker: '结城美柑',
      text: '老哥，别愣着。先带她进最近的服装店。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '咦？你们为什么会在这里？',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '你准备好的解释一下全堵在喉咙里。美柑已经抱来一套衣服，把菈菈推进试衣间。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '结城美柑',
      text: '菈菈刚从很远的地方来，我们带她熟悉彩南町。衣服不合适，所以临时来买一套。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '就、就是这样。绝对不是你刚才想到的那种事。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '我还什么都没说呢。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '换上店里买来的衣服后，菈菈抱着兔子跑回来。春菜与她打了招呼，气氛却仍有些拘谨。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '结城美柑',
      text: '春菜姐，明天要不要也和我们一起？四个人出去会更热闹。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '明天？我跟着去，不会打扰你们吗？',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '来嘛，春菜！我还没去过地球的水族馆，我们明天一起去看鱼吧！',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '结城美柑',
      text: '那就水族馆。我这里正好有四张票。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '好。那明天见。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '菈菈高兴得差点又让沛凯换装。美柑及时按住她，约定停在了第二天的水族馆门口。',
      presentation: {
        sceneId: 'townStreet',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
  ],
} as const satisfies StoryEpisodeActDefinition;
