import type { StoryEpisodeActDefinition } from '../../../episodeTemplate';

export const EPISODE_03_ACT_01 = {
  id: 'ep03.act1-transfer-and-outing-plan',
  title: '菈菈拜托你低调一点',
  trigger: { date: { year: 2008, month: 4, day: 11 }, actionNumber: 1 },
  timeCost: 'whole-day',
  plotLore: {
    worldbookName: '出包王女',
    entryOrder: 155,
    entryName: '剧情第三集·第一幕',
    rootTag: 'To LOVE-Ru TV Episode 03 Act 01',
    kind: 'plot',
  },
  loreSection: '第一幕·低调一点',
  characterLoreIds: ['lala', 'haruna', 'mikan', 'riko'],
  presentation: {
    sceneIds: ['rooftop', 'school', 'home'],
    cast: [
      { characterId: 'lala', portraitIds: ['arrival-default', 'school-uniform'] },
      { characterId: 'haruna', portraitIds: ['school-uniform'] },
      { characterId: 'mikan', portraitIds: ['arrival-default'] },
      { characterId: 'riko', portraitIds: ['school-uniform'] },
    ],
    portraitRules: [
      {
        sceneId: 'rooftop',
        characterId: 'lala',
        portraitId: 'school-uniform',
        outsideScenePortraitId: 'arrival-default',
      },
      {
        sceneId: 'school',
        characterId: 'lala',
        portraitId: 'school-uniform',
        outsideScenePortraitId: 'arrival-default',
      },
    ],
  },
  generation: {
    minimumLineCount: 30,
    requiredSceneSequence: ['rooftop', 'school', 'rooftop', 'school', 'home'],
  },
  fallbackBeats: [
    {
      speaker: null,
      text: '下课铃刚响，你便把新来的菈菈带上屋顶。教室里的议论隔着门都压不住。',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '你怎么突然转到我们学校来了？手续又是怎么办下来的？',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '因为我想一直陪在你身边呀！',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '先别说得这么轻松。转校手续不可能凭一句话就办好吧？',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '我去拜托校长了。他说这么可爱的孩子当然没问题！',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '那个校长果然有问题……总之，千万别暴露外星人的事。在学校低调一点。',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'serious',
        effect: 'shake',
      },
    },
    {
      speaker: null,
      text: '第一节课，菈菈画出的“普通风景”里挤满飞船。老师盯着画纸看了半天，只能夸她想象力丰富。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '夕崎梨子',
      text: '这就是你教她的低调？看来还得从“什么叫普通”开始讲。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '体育课更糟。菈菈轻轻一投，球越过操场围网，远得连落点都看不见。四周的人一下围了过来。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: '里纱',
      text: '新同学也太有意思了。来，让我看看还有哪里和我们不一样。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '里纱从背后抱住菈菈，手还想继续乱探。未央赶紧把她拽开，菈菈倒是一脸好奇。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'shake',
      },
    },
    {
      speaker: '未央',
      text: '别一见面就动手啦，会把人吓到的。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '菈菈越受欢迎，男生们看你的眼神就越刺。粉笔、空盒和纸团很快从四面八方飞了过来。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'shake',
      },
    },
    {
      speaker: '猿山',
      text: '为什么她偏偏整天黏着你啊！',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'shake',
      },
    },
    {
      speaker: '你',
      text: '我才是最想问这个的人！还有，别再扔了！',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: null,
      text: '放学前，你顶着满头纸屑再次把菈菈叫上屋顶。本想严厉一点，开口时却只剩疲惫。',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '我不是刚说过不要太显眼吗？',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'serious',
        effect: 'shake',
      },
    },
    {
      speaker: '菈菈',
      text: '对不起。我下次一定会注意！',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'serious',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '回到教室，梨子把你的书包递过来，又朝门边抬了抬下巴。春菜还没有走。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '夕崎梨子',
      text: '想解释就趁现在。你再拖一天，误会可不会自己消失。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'riko',
        portraitId: 'school-uniform',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '梨子先走了。春菜抱着书站在教室门边，像是等了很久，又像只是碰巧停在那里。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '春菜，你是不是有话想说？',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '没、没什么。我只是想问，你觉得菈菈同学怎么样？',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '她当然是好人，可婚约那件事根本不是大家想的那样。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '可是……我觉得你们很般配。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '你愣住了。春菜明明在笑，手指却把书角压出一道弯痕。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '找到你了！美柑说饭快好了，我们回家吧！',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'lala',
        portraitId: 'school-uniform',
        expressionId: 'happy',
        effect: 'flash',
      },
    },
    {
      speaker: '你',
      text: '等一下，我和春菜还没说完——',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '没关系。你们先回去吧。',
      presentation: {
        sceneId: 'school',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '回到家，你趴在桌边，一口饭也没动。菈菈绕着你看了两圈，还是不明白那句话为什么让你这么没精神。',
      presentation: {
        sceneId: 'home',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '结城美柑',
      text: '你，闷着也想不明白。明天带菈菈去彩南町转转吧，她对地球还什么都不熟。',
      presentation: {
        sceneId: 'home',
        focusCharacterId: 'mikan',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'none',
      },
    },
  ],
} as const satisfies StoryEpisodeActDefinition;
