import type { StoryActDefinition } from '../../../storyTypes';

export const EPISODE_01_ACT_02 = {
  id: 'ep01.act2-bathroom',
  title: '浴室里的王女',
  actionPointsRemaining: 0,
  loreSection: '第二幕·浴室里的王女',
  characterLoreIds: ['lala'],
  presentation: {
    sceneIds: ['washroom', 'home', 'bedroom', 'rooftop', 'nightStreet', 'park', 'schoolRoad'],
    cast: [
      { characterId: 'lala', portraitIds: ['arrival-default', 'washroom-swimsuit'] },
      { characterId: 'haruna', portraitIds: ['school-uniform'] },
      { characterId: 'riko', portraitIds: ['school-uniform'] },
    ],
    portraitRules: [
      {
        sceneId: 'washroom',
        characterId: 'lala',
        portraitId: 'washroom-swimsuit',
        outsideScenePortraitId: 'arrival-default',
      },
    ],
  },
  generation: {
    minimumLineCount: 30,
    requiredSceneSequence: ['washroom', 'home', 'bedroom', 'rooftop', 'nightStreet', 'park', 'schoolRoad'],
  },
  fallbackBeats: [
    {
      speaker: null,
      text: '浴缸轰然炸开，水花和蒸汽糊满视野。粉发少女从白光里冒出来，扶着缸沿长长呼出一口气。',
      presentation: {
        sceneId: 'washroom',
        focusCharacterId: 'lala',
        portraitId: 'washroom-swimsuit',
        expressionId: 'happy',
        effect: 'flash',
      },
    },
    {
      speaker: '菈菈',
      text: '逃脱成功！',
      presentation: {
        sceneId: 'washroom',
        focusCharacterId: 'lala',
        portraitId: 'washroom-swimsuit',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '唔噢噢噢噢？！',
      presentation: {
        sceneId: 'washroom',
        focusCharacterId: 'lala',
        portraitId: 'washroom-swimsuit',
        expressionId: 'neutral',
        effect: 'shake',
      },
    },
    {
      speaker: null,
      text: '门外脚步逼近。你慌忙转头，再看浴缸时只剩晃动的水面，刚才的少女已经不见了。',
      presentation: {
        sceneId: 'home',
        focusCharacterId: null,
        portraitId: null,
        expressionId: null,
        effect: 'none',
      },
    },
    {
      speaker: '美柑',
      text: '叫得整栋房子都听见了。浴室里真的有人？',
      presentation: {
        sceneId: 'home',
        focusCharacterId: null,
        portraitId: null,
        expressionId: null,
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '你回到卧室，刚才消失的少女正裹着借来的浴巾坐在那里，一条尾巴在身后自在地摆动。',
      presentation: {
        sceneId: 'bedroom',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '我叫菈菈。刚才谢谢你啦！',
      presentation: {
        sceneId: 'bedroom',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '尾、尾巴？！你看到满月也不会变身吧？',
      presentation: {
        sceneId: 'bedroom',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'shake',
      },
    },
    {
      speaker: '菈菈',
      text: '不会呀。我用跳跳瓦普君逃出来，可它只能传送生物，目的地也是随机的。',
      presentation: {
        sceneId: 'bedroom',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'neutral',
        effect: 'none',
      },
    },
    {
      speaker: '沛凯',
      text: '菈菈大人，我总算追上您了。还有，这位地球人看起来实在不怎么可靠。',
      presentation: {
        sceneId: 'bedroom',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '沛凯展开成一套服装包住菈菈。下一秒，窗户连着墙面一同震响，两名追兵闯进卧室。',
      presentation: {
        sceneId: 'bedroom',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: '马乌尔',
      text: '终于找到您了。请跟我们回去，公主殿下。',
      presentation: {
        sceneId: 'bedroom',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '追兵伸手抓住菈菈。你来不及细想，一脚把地上的足球踢向他，拉住她便从窗口冲了出去。',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: '你',
      text: '眼看着女孩子被强行带走，我怎么可能什么都不做！',
      presentation: {
        sceneId: 'rooftop',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '你赤脚踩过一片片屋顶，手里还拉着菈菈。正在遛狗的春菜抬起头，正好看见你们从夜空掠过。',
      presentation: {
        sceneId: 'nightStreet',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'panic',
        effect: 'none',
      },
    },
    {
      speaker: '西连寺春菜',
      text: '刚才那个……是你吗？旁边的女孩子又是谁？',
      presentation: {
        sceneId: 'nightStreet',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: null,
      text: '追兵在公园里再次堵住去路，一艘巨大的飞船随即压到头顶。舱门打开，披着铠甲的萨斯丁落在两人面前。',
      presentation: {
        sceneId: 'park',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'none',
      },
    },
    {
      speaker: '萨斯丁',
      text: '菈菈大人，离家出走到此为止。您是戴比路克第一公主，不能再逃避陛下安排的相亲。',
      presentation: {
        sceneId: 'park',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'serious',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '我才不要被他们带回去。GOGO真空君，启动！',
      presentation: {
        sceneId: 'park',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'flash',
      },
    },
    {
      speaker: null,
      text: '萨斯丁、两名追兵、长椅、垃圾桶和你一起被吸上半空。真空君越转越快，整片公园都被狂风搅成一团。',
      presentation: {
        sceneId: 'park',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'panic',
        effect: 'shake',
      },
    },
    {
      speaker: '菈菈',
      text: '糟糕，我忘记怎么让它停下来了！',
      presentation: {
        sceneId: 'park',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'shy',
        effect: 'shake',
      },
    },
    {
      speaker: null,
      text: '第二天上学路上，你顶着绷带遇见春菜。她刚问起昨晚的事，你便闭紧眼睛，抢在勇气消失前喊了出来。',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'worried',
        effect: 'none',
      },
    },
    {
      speaker: '你',
      text: '我喜欢你！请和我交往！',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'haruna',
        portraitId: 'school-uniform',
        expressionId: 'shy',
        effect: 'none',
      },
    },
    {
      speaker: '菈菈',
      text: '原来你喜欢我！那我们结婚吧！',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'flash',
      },
    },
    {
      speaker: '你',
      text: '结、结婚？！',
      presentation: {
        sceneId: 'schoolRoad',
        focusCharacterId: 'lala',
        portraitId: 'arrival-default',
        expressionId: 'happy',
        effect: 'shake',
      },
    },
  ],
} as const satisfies StoryActDefinition;
