import type { StoryActDefinition } from '../../../storyTypes';

export const LALA_ARRIVAL_ACT_02 = {
  id: 'ep01.act2-bathroom',
  title: '浴室里的王女',
  actionPointsRemaining: 0,
  opening: '承接浴室门后的白光、水花与蒸汽，菈菈随机传送出现。',
  ending: '次日菈菈完整误接你原本给春菜的告白，公开宣布婚约，众人错愕。',
  charactersWithLore: ['菈菈'],
  presentation: {
    initialBackground: 'washroom',
    transitions: [
      { atProgress: 0.4, background: 'night' },
      { atProgress: 0.8, background: 'school' },
    ],
  },
  fallbackBeats: [
    {
      speaker: null,
      text: '白光在浴室里炸开，水汽被卷成一圈涡流，一个粉色长发的少女咚地落进浴缸。',
      lalaExpression: 'f',
      background: 'washroom',
      effect: 'flash',
    },
    {
      speaker: '你',
      text: '等一下！你是从哪里掉进来的？！',
      lalaExpression: 'f',
      background: 'washroom',
      effect: 'shake',
    },
    {
      speaker: '菈菈',
      text: '传送成功！你好，我是菈菈！虽然落点好像稍微偏了一点点。',
      lalaExpression: 'a',
      background: 'washroom',
      effect: 'none',
    },
    {
      speaker: null,
      text: '她身后的尾巴轻轻一摆，圆滚滚的机械装置从窗口飞进来，认真得像在宣布实验报告。',
      lalaExpression: 'b',
      background: 'washroom',
      effect: 'none',
    },
    {
      speaker: '沛凯',
      text: '菈菈大人，随机传送的误差依旧十分稳定。请先让我解决服装问题。',
      lalaExpression: 'c',
      background: 'washroom',
      effect: 'none',
    },
    {
      speaker: null,
      text: '整齐的脚步声撞进院子。亲卫队破门而入，菈菈抓住你的手腕，转身就往屋顶跑。',
      lalaExpression: 'e',
      background: 'night',
      effect: 'shake',
    },
    {
      speaker: '萨斯丁',
      text: '第一公主，请结束这场离家出走。戴比路克王位和相亲安排都在等您。',
      lalaExpression: 'b',
      background: 'night',
      effect: 'none',
    },
    {
      speaker: '你',
      text: '她已经说了不想回去。至少让她自己决定要过什么生活！',
      lalaExpression: 'd',
      background: 'night',
      effect: 'none',
    },
    {
      speaker: '菈菈',
      text: '说得好！那就交给我的GOGO真空君吧！',
      lalaExpression: 'a',
      background: 'night',
      effect: 'flash',
    },
    {
      speaker: null,
      text: '机器越转越快，卫兵、晾衣杆和你一起离地半尺。下一秒，黑烟和惨叫同时盖过屋顶。',
      lalaExpression: 'f',
      background: 'night',
      effect: 'shake',
    },
    {
      speaker: null,
      text: '第二天，春菜在校门前问起昨夜的骚动。你看见机会重新站到眼前，索性闭紧双眼。',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: '你',
      text: '我喜欢你！请和我交往！',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: null,
      text: '你睁开眼。春菜站在两步之外，而菈菈正好从侧面探到你面前，绿眼睛亮得像信号灯。',
      lalaExpression: 'c',
      background: 'school',
      effect: 'flash',
    },
    {
      speaker: '菈菈',
      text: '原来你也喜欢我！太好了，那我们结婚吧！',
      lalaExpression: 'c',
      background: 'school',
      effect: 'none',
    },
  ],
} as const satisfies StoryActDefinition;
