import type { StoryActDefinition } from '../../../storyTypes';

export const LALA_ARRIVAL_ACT_01 = {
  id: 'ep01.act1-falling-star',
  title: '放学后的坠落光',
  actionPointsRemaining: 1,
  opening: '放学后的旧校舍天台上，你与春菜都差点说出告白。',
  ending: '你回到家打开浴室门，白光先一步填满视线。',
  charactersWithLore: [],
  presentation: {
    initialBackground: 'school',
    transitions: [
      { atProgress: 0.65, background: 'night' },
      { atProgress: 0.8, background: 'washroomDoor' },
      { atProgress: 1, background: 'washroom' },
    ],
  },
  fallbackBeats: [
    {
      speaker: null,
      text: '放学后的旧校舍天台上，风卷着几片枯叶打转，夕阳把你和春菜的影子拉得很长。',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: '西连寺春菜',
      text: '那个……把你叫到这里来……其实我是想说……',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: null,
      text: '不久前，夕崎梨子还在鞋柜旁拍着你的背，催你别再临阵退缩。现在那点勇气全堵在喉咙里。',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: null,
      text: '头顶的云层忽然被白光剖开，破空声压下春菜的惊呼，一团拖着火花的光擦过教学楼。',
      lalaExpression: null,
      background: 'school',
      effect: 'flash',
    },
    {
      speaker: '你',
      text: '危险！',
      lalaExpression: null,
      background: 'school',
      effect: 'shake',
    },
    {
      speaker: null,
      text: '你把春菜拽向身侧，两人跌在粗糙的防滑地砖上。后山方向升起黑烟，警报声在彩南町此起彼伏。',
      lalaExpression: null,
      background: 'school',
      effect: 'shake',
    },
    {
      speaker: '猿山',
      text: '喂！天台上的！快下来！听说是陨石掉下来了，别在那发呆啦！',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: '西连寺春菜',
      text: '那个，你刚才……想说什么？',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: '你',
      text: '没什么，明天再说吧。快走。',
      lalaExpression: null,
      background: 'school',
      effect: 'none',
    },
    {
      speaker: null,
      text: '你满身汗和尘土地回到家，只想把这场尴尬又惊险的骚动全冲进下水道。',
      lalaExpression: null,
      background: 'night',
      effect: 'none',
    },
    {
      speaker: null,
      text: '你来到浴室门前，手刚搭上门把，门缝里便漏出一线不属于家中的白光。',
      lalaExpression: null,
      background: 'washroomDoor',
      effect: 'none',
    },
    {
      speaker: null,
      text: '门把手转开的瞬间，刺眼白光越过粉紫色水汽和浴缸，把整个视野彻底吞没。',
      lalaExpression: null,
      background: 'washroom',
      effect: 'flash',
    },
  ],
} as const satisfies StoryActDefinition;
